export const FETCH_USER = 'fetch_user'
export const UPDATE_USER = 'update_user'
export const FETCH_USER_CART = 'fetch_user_cart'
export const ALL_PRODUCTS = 'all_products'
export const UPDATE_CART = 'update_cart'
export const CONVERT_CART = 'convert_cart'
export const UPDATE_FORM_FIELDS = 'update_form_fields'
export const CLEAR_FIELDS = 'clear_fields'